In [15]:
# from datasets import load_dataset
import numpy as np

import pandas as pd
# df = load_dataset('roman-bushuiev/MassSpecGym', data_files='data/MassSpecGym.tsv', split='train')\
#     .shuffle(seed=42)\
#     .select(range(500)).to_pandas()
df = pd.read_parquet('msg_rand500.parquet')

In [7]:
# df.to_parquet("msg_rand500.parquet")
df

identifier                                                mzs  \
0    MassSpecGymID0052279  114.0915,149.0709,176.1072,191.0815,192.0768,1...   
1    MassSpecGymID0167344  75.023003,77.038002,89.038002,91.054001,101.03...   
2    MassSpecGymID0400927  91.054169,93.069809,95.049164,95.085434,97.064...   
3    MassSpecGymID0055045  42.0338,44.0495,58.0651,69.0448,71.0604,83.060...   
4    MassSpecGymID0227317  41.038471,41.270458,43.054085,44.049362,71.085...   
..                    ...                                                ...   
495  MassSpecGymID0085532       129.1149,284.9764,288.0453,296.9765,365.0393   
496  MassSpecGymID0237374  135.031662,153.012909,153.018829,153.042191,15...   
497  MassSpecGymID0118480  63.021999,65.037003,74.013,75.021004,76.028999...   
498  MassSpecGymID0107120  119.049332,131.049042,132.081802,135.043106,14...   
499  MassSpecGymID0240052  53.03907,65.038963,73.959297,75.321404,77.0388...   

                                           intensities  \
0    0.0013355700000000001,0.00890994,0.00139608,0....   
1    0.059,0.006,1.0,0.046,0.052,0.038,0.427,0.126,...   
2    0.14086688273294626,0.11596669766096218,0.0075...   
3    1.0,0.3083083083083083,0.3383383383383383,0.02...   
4    0.00196,0.00248,0.00226,0.041749999999999995,0...   
..                                                 ...   
495    0.08955041,1.0,0.07856544,0.13605268,0.14168902   
496  0.01366,0.00642,0.0046500000000000005,1.0,0.00...   
497  0.038,0.048,0.014,0.091,0.065,0.716,0.11,0.031...   
498  0.022716763005780346,0.017687861271676302,0.01...   
499  0.010653631038886687,0.004991940811203593,0.00...   

                                                smiles        inchikey  \
0       CC(C)C1(C(=O)NC(=N1)C2=C(C=C(C=N2)COC)C(=O)O)C  NUPJIGQFXCQJBK   
1    C1=C2C3=C(C(=C1O)O)OC(=O)C4=CC(=C(C(=C43)OC2=O...  AFSDNFLWKVMVRB   
2    CCCCCCCCCCCCCCCC/C=C\OC[C@H](COP(=O)(O)OCCN)OC...  URPXXNCTXCOATD   
3                                   C1N2CN3CN1CN(C2)C3  VKYKSIONXSXAKP   
4    CC(C)(C)CNCCN1C2=C(C(=NC=C2)N)N=C1SC3=CC4=C(C=...  RVJIQAYFTOPTKK   
..                                                 ...             ...   
495  CC1(CCCO1)CN(C)S(=O)(=O)C2=CC(=C(C=C2)Cl)S(=O)...  SMNOERSLNYGGOU   
496  C1=CC(=C(C=C1NCC2=C(C(=C(C(=C2F)F)C(F)(F)F)F)F...  HABROHXUHNHQMY   
497      CN1CCC23CC(=O)C(=CC2C1CC4=C3C(=C(C=C4)OC)O)OC  INYYVPJSBIVGPH   
498  CN1CCC2=CC3=C(C=C2[C@@H]1[C@@H]4C5=C(C(=C(C=C5...  JZUTXVTYJDCMDU   
499       COC1=CC(=C(C=C1)OC)C2=C(C(=O)C3=CC=CC=C3O2)O  XKHRVIACZOQQNZ   

            formula precursor_formula  parent_mass  precursor_mz  adduct  \
0        C15H19N3O4        C15H20N3O4   305.137524     306.14480  [M+H]+   
1           C14H6O8           C14H7O8   302.002724     303.01000  [M+H]+   
2        C43H78NO7P        C43H79NO7P   751.551724     752.55900  [M+H]+   
3           C6H12N4           C6H13N4   140.106224     141.11350  [M+H]+   
4       C22H30N6O2S       C22H31N6O2S   442.215094     443.22237  [M+H]+   
..              ...               ...          ...           ...     ...   
495  C13H19ClN2O5S2    C13H20ClN2O5S2   382.042424     383.04970  [M+H]+   
496      C15H8F7NO3        C15H9F7NO3   383.039244     384.04652  [M+H]+   
497       C19H23NO4         C19H24NO4   329.162724     330.17000  [M+H]+   
498       C21H21NO6         C21H22NO6   383.143724     384.15100  [M+H]+   
499        C17H14O5          C17H15O5   298.083724     299.09100  [M+H]+   

    instrument_type  collision_energy   fold  simulation_challenge  
0          Orbitrap         21.430136  train                  True  
1          Orbitrap               NaN  train                 False  
2          Orbitrap               NaN  train                 False  
3          Orbitrap         21.167025  train                  True  
4          Orbitrap         60.000000  train                  True  
..              ...               ...    ...                   ...  
495        Orbitrap         91.931928  train                  True  
496

In [10]:
for instrument_type, gp in df.groupby('instrument_type'):
    pass

gp

identifier                                                mzs  \
7    MassSpecGymID0063121  61.02597,81.0369,85.03058,97.02452,97.03021,10...   
8    MassSpecGymID0144975  117.0567,122.0707,142.064,149.0803,153.1127,16...   
10   MassSpecGymID0038875  103.054291,105.069901,115.054596,119.085739,13...   
12   MassSpecGymID0397724  41.038582,51.02293,65.038582,69.069878,95.0491...   
13   MassSpecGymID0008505  83.0536,97.0654,109.0641,123.0793,173.1318,177...   
..                    ...                                                ...   
480  MassSpecGymID0054414  39.0222,51.0222,53.0377,54.0334,63.0219,65.037...   
482  MassSpecGymID0039661  169.0505,183.0404,185.0494,190.0455,191.0521,2...   
487  MassSpecGymID0099670  93.07141,94.0621,94.06935,96.0816,107.08838,10...   
488  MassSpecGymID0051601  39.0233,50.0152,51.0233,52.0296,55.0182,63.023...   
498  MassSpecGymID0107120  119.049332,131.049042,132.081802,135.043106,14...   

                                           intensities  \
7    0.061,0.076,0.073,0.098,0.08199999999999999,0....   
8    0.013586959999999999,0.24945652,0.015217389999...   
10   0.00757036120952828,0.01632207052045968,0.1165...   
12   0.1322,0.11320000000000001,0.3093,0.1137,0.168...   
13   0.05405405405405406,1.0,0.6126126126126126,0.0...   
..                                                 ...   
480  0.05005005005005005,0.01701701701701702,0.1011...   
482  0.01701701701701702,0.028028028028028028,0.008...   
487  0.006999999999999999,0.021,0.01,0.008,0.008,0....   
488  0.07807807807807808,0.021021021021021023,0.145...   
498  0.022716763005780346,0.017687861271676302,0.01...   

                                                smiles        inchikey  \
7    C1=CC(=CC=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O[C@...  JPUKWEQWGBDDQB   
8    C1CCN(C1)C2=NC(=NC(=N2)N3CC4CC(C3)C5=CC=CC(=O)...  NZPAMSHQYRPUFB   
10           CC(C)(C)C#C/C=C/CN(C)CC1=CC=CC2=CC=CC=C21  DOMXUEMWDBAQBQ   
12   CC(=CCC1=C(C(=C2C(=C1O)C(=O)C3=C(O2)C=C(C=C3)O...  HHHZYUKPVCUMDR   
13   CC(=O)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC4...  RJKFOVLPORLFTN   
..                                                 ...             ...   
480                       C1=CC=C(C=C1)NC2=CC=C(C=C2)O  JTTMYKSFKOOQLP   
482  C1=CC(=CC(=C1)OC2=C(C=CC=N2)C(=O)NC3=C(C=C(C=C...  WYEHFWKAOXOVJD   
487  C/C=C\1/C[C@H]([C@@](C(=O)OCC2=CCN3[C@H]2[C@@H...  HKODIGSRFALUTA   
488                              COC1=CC=C(C=C1)C=CC=O  AXCXHFKZHDEKTP   
498  CN1CCC2=CC3=C(C=C2[C@@H]1[C@@H]4C5=C(C(=C(C=C5...  JZUTXVTYJDCMDU   

          formula precursor_formula  parent_mass  precursor_mz  adduct  \
7       C21H20O11         C21H21O11   448.100562    449.107838  [M+H]+   
8       C22H29N7O         C22H30N7O   407.243424    408.250700  [M+H]+   
10        C21H25N           C21H26N   291.199724    292.207000  [M+H]+   
12       C23H24O5          C23H25O5   380.162724    381.170000  [M+H]+   
13       C21H30O2          C21H31O2   314.224624    315.231900  [M+H]+   
..            ...               ...          ...           ...     ...   
480      C12H11NO          C12H12NO   185.084124    186.091400  [M+H]+   
482  C19H11F5N2O2      C19H12F5N2O2   394.074024    395.081300  [M+H]+   
487     C18H25NO5         C18H26NO5   335.173273    336.180549  [M+H]+   
488      C10H10O2          C10H11O2   162.068124    163.075400  [M+H]+   
498     C21H21NO6         C21H22NO6   383.143724    384.151000  [M+H]+   

    instrument_type  collision_energy   fold  simulation_challenge  
7              QTOF              50.0  train                  True  
8              QTOF              40.0  train                  True  
10             QTOF               NaN  train                 False  
12             QTOF               NaN  train                 False  
13             QTOF              10.0  train                  True  
..              ...               ...    ...                   ...  
480            QTOF              60.0  train                  True  
482            QTOF        

In [11]:
from msbuddy import Msbuddy, MsbuddyConfig
from msbuddy.base import MetaFeature, Spectrum

In [30]:
config = MsbuddyConfig(ms_instr=instrument_type.lower(),
                     ppm=True, ms1_tol=5, ms2_tol=10, halogen=True)

In [13]:
msb = Msbuddy(config)

msbuddy: molecular formula annotation for MS-based small molecule analysis.
Developed and maintained by Shipei Xing.


In [16]:
def as_metafeature(sp: pd.Series) -> MetaFeature:
    mz_array = np.array(list(map(float, sp.mzs.split(','))))
    int_array = np.array(list(map(float, sp.intensities.split(','))))
    ms2_spec = Spectrum(
        mz_array=mz_array,
        int_array=int_array,
    )

    metafeature = MetaFeature(
        identifier = 0,  # unique identifier for the MetaFeature object
        mz = sp.precursor_mz,  # precursor m/z
        rt = None,  # retention time, can be None if not available
        charge = 1,  # precursor charge
        adduct = sp.adduct,
        ms2 = ms2_spec)
    return metafeature

In [33]:
mf_ = as_metafeature(gp.iloc[0])

In [34]:
msb.add_data([mf_])

In [35]:
msb.annotate_formula()

1 query loaded.
1 batch in total.
Batch 1/1:
Subformula assignment: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
Candidate formula ranking...
FDR calculation: 100%|██████████| 1/1 [00:00<00:00, 1311.95it/s]
Job finished.


# Inside

In [44]:
###
# n_batch = msb._annotate_formula_prepare()
###
data = [mf_]
data = [mf for mf in data if 1 < mf.mz < 1500] # .mz is precursor mz
assert data
n_batch = int(np.ceil(len(data) / config.batch_size))
print(f"{n_batch} batches in total." if n_batch > 1 else "1 batch in total.")

##
# for n in range(n_batch):
#     msb._annotate_formula_main_batch(n, n_batch)
##

start_idx, end_idx = 0, 1

####
##  -> self._preprocess_and_generate_candidate_formula(start_idx, end_idx)
####
### -> -> _preprocess_and_gen_cand_nonparallel
### -> -> ->  _generate_candidate_formula

mf = data[0]
## >>>> mf.data_preprocess()

# mf.data_preprocess()

# mf.ms1_processed = 
mf.ms1_raw, mf.ms2_raw

1 batch in total.


(None, <msbuddy.base.Spectrum at 0x7f080d3c9190>)

In [46]:
from msbuddy.base import ProcessedMS2

## Inside mf
mf.ms2_processed = ProcessedMS2(
    mf.mz, mf.ms2_raw,
    config.ms2_tol, config.ppm, 
    config.rel_int_denoise_cutoff, 
    config.top_n_per_50_da)

In [66]:
ps = config # convenience
# >>> gen_candidate_formula
assert mf.ms2_processed is not None

# >>>> _gen_candidate_formula_from_ms2
# ms2_cand_form_ls, ms2_cand_form_str_ls = _gen_candidate_formula_from_ms2(
#     mf, ppm, ms1_tol, ms2_tol,
#     ele_lower_limit,
#     ele_upper_limit, db_mode, gd)

mf.ms2_processed.normalize_intensity(method='sum')

In [70]:
assert str(mf.adduct.net_formula) == 'H'

In [72]:
ms1_tol, ppm = config.ms1_tol, config.ppm

ms1_abs_tol = ms1_tol if not ppm else ms1_tol * mf.mz * 1e-6

ms1_abs_tol, ppm

(0.004491078379, True)

In [86]:
from math import ceil

candidate_space_list = []
existing_cand_str_list = []
for i in range(len(mf.ms2_processed.mz_array)):
    frag_mz = mf.ms2_processed.mz_array[i]
    nl_mz = mf.mz - frag_mz
    print(f"{i}, {frag_mz:.5f}, {nl_mz:.5f}, {mf.mz:.5f}")

    ### >>>> frag_form_list, nl_form_list = \
    #      _query_frag_nl_pair(#     frag_mz, nl_mz, 
    #       mf.adduct.pos_mode, na_bool, k_bool, ms2_tol, ppm, db_mode, gd)
    # frag_mz is smaller so go with 
    # frag_form_list = query_fragnl_mass(
    #       frag_mz, True, pos_mode, na_bool, k_bool,
    #       ms2_tol, ppm, db_mode, gd)
    mass = frag_mz
    mz_tol = config.ms2_tol
    
    mass_tol = mass * mz_tol / 1e6 if config.ppm else mz_tol
    formulas = []
    print(f"Mass tol {mass_tol:.6f}")
    # t_mass, start_idx, end_idx = _calc_t_mass_db_idx(
    # mass, fragment, False, 0, pos_mode, mass_tol)
    # formulas.extend(_func_b(t_mass, mass_tol, start_idx, end_idx, fragment, False,
    #                         False, False, pos_mode, db_mode, gd))
    fragment = True
    radical = False
    pos_mode = True
    convert_mass = 0.0
    t_mass = None
    if fragment:
        if not radical:
            print("Fragment, not radical")
            t_mass = mass - convert_mass - 1.007276 if pos_mode \
                else mass - convert_mass + 1.007276
            formulas.extend(
                
            )
    start_idx = int((t_mass - mass_tol) * 10)
    end_idx = ceil((t_mass + mass_tol) * 10)
    print(t_mass, start_idx, end_idx)
    break

0, 61.02597, 388.08187, 449.10784
Mass tol 0.001221
Fragment, not radical
60.01869445898438 600 601


In [65]:
ls = np.random.uniform(0, 1, 5).round(3)
for _ in range(10):
    print(ls)
    ls /= ls.sum()
    print(ls)
    ls /= ls.max()

[0.697 0.703 0.803 0.234 0.066]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]
[0.86799502 0.875467   1.         0.29140722 0.08219178]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]
[0.86799502 0.875467   1.         0.29140722 0.08219178]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]
[0.86799502 0.875467   1.         0.29140722 0.08219178]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]
[0.86799502 0.875467   1.         0.29140722 0.08219178]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]
[0.86799502 0.875467   1.         0.29140722 0.08219178]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]
[0.86799502 0.875467   1.         0.29140722 0.08219178]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]
[0.86799502 0.875467   1.         0.29140722 0.08219178]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]
[0.86799502 0.875467   1.         0.29140722 0.08219178]
[0.27846584 0.28086296 0.32081502 0.09348781 0.02636836]

In [54]:
mf.ms2_processed.int_array

array([0.061, 0.076, 0.073, 0.098, 0.082, 0.18 , 0.332, 0.11 , 0.107,
       0.149, 0.116, 0.104, 1.   , 0.137, 0.247, 0.125, 0.101, 0.064,
       0.067, 0.296, 0.116, 0.076, 0.064, 0.073, 0.201, 0.091, 0.076,
       0.183, 0.238, 0.125, 0.076], dtype=float32)

In [55]:
mf.ms2_processed.int_array / mf.ms2_processed.int_array.max()

array([0.061, 0.076, 0.073, 0.098, 0.082, 0.18 , 0.332, 0.11 , 0.107,
       0.149, 0.116, 0.104, 1.   , 0.137, 0.247, 0.125, 0.101, 0.064,
       0.067, 0.296, 0.116, 0.076, 0.064, 0.073, 0.201, 0.091, 0.076,
       0.183, 0.238, 0.125, 0.076], dtype=float32)

In [24]:
pd.DataFrame(msb.get_summary())

identifier          mz    rt  adduct formula_rank_1  estimated_fdr  \
0           0  449.107838  None  [M+H]+      C21H20O11       0.006973   

  formula_rank_2 formula_rank_3 formula_rank_4 formula_rank_5  
0    C14H20N6O9S  C16H25N4O5PS2   C23H17FN4O3S   C17H16F4N4O6